services:
  # development container
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    stdin_open: true

  # database
  mysql_db:
    hostname: mysql_db
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ../db:/docker-entrypoint-initdb.d

  # web server
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-webserver
    hostname: webserver
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
    ports:
      - 8080:80
    volumes:
      - ./apache-virtualhost.conf:/etc/apache2/sites-enabled/00-default.conf
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../src:/var/www/html
    depends_on: [mysql_db]

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DATABASE_HOST}
      - PMA_USER=${DATABASE_USER}
      - PMA_PASSWORD=${DATABASE_PASSWORD}
    depends_on: [mysql_db]
    volumes:
      - ./phpmyadmin/darkwolf:/var/www/html/themes/darkwolf
