name: GitHub Actions Demo
on:
  push:
    tags:
      - "v*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set filename
        run: echo "FILENAME=Woliński_4a_${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: mkdir $FILENAME
      - run: cp ./src "${{env.FILENAME}}/php" -r
      - run: cp ./db "${{env.FILENAME}}/db" -r
      - uses: vimtor/action-zip@v1
        with:
          files: "${{env.FILENAME}}"
          recursive: false
          dest: "${{env.FILENAME}}.zip"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{env.FILENAME}}.zip"