name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir "Seweryn_Woliński-$GITHUB_REF_NAME"
      - run: cp ./src "Seweryn_Woliński-$GITHUB_REF_NAME/php" -r
      - run: cp ./db "Seweryn_Woliński-$GITHUB_REF_NAME/db" -r
      - uses: vimtor/action-zip@v1
        with:
          files: "Sewryn_Woliński-$GITHUB_REF_NAME"
          recursive: false
          dest: "Sewryn_Woliński-$GITHUB_REF_NAME.zip"
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: New version
          files: "Sewryn_Woliński-$GITHUB_REF_NAME.zip"