name: GitHub Actions Demo
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir "Seweryn_Woliński-$GITHUB_REF_NAME"
      - run: cp ./src "Seweryn_Woliński-$GITHUB_REF_NAME/php" -r
      - run: cp ./db "Seweryn_Woliński-$GITHUB_REF_NAME/db" -r
      - uses: vimtor/action-zip@v1
        with:
          files: "Sewryn_Woliński-$GITHUB_REF_NAME"
          recursive: false
          dest: "Sewryn_Woliński-$GITHUB_REF_NAME.zip"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "Sewryn_Woliński-$GITHUB_REF_NAME.zip"